# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
cpp_bmpop <- function(data, sig, rytpar, alpha, k, perd) {
    .Call('CATkit_cpp_bmpop', PACKAGE = 'CATkit', data, sig, rytpar, alpha, k, perd)
}

#' @export
cpp_test <- function(X) {
    .Call('CATkit_cpp_test', PACKAGE = 'CATkit', X)
}

